# Generated by Django 6.0.7 on 2026-08-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_project_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Beginner', max_length=20),
        ),
    ]
